services:
  db:
    image: postgres:16
    container_name: marketplace_gp_db
    restart: always
    environment:
      POSTGRES_USER: ets
      POSTGRES_PASSWORD: iyan0010
      POSTGRES_DB: marketplace_gp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: